-- Generated by Premade Nodes: RotateOnTick
speed = 90.0
function OnStart(id) Print("Rotate premade ready") end
function OnTick(id, dt)
  local x,y,z = GetRotation(id)
  y = y + speed * dt
  SetRotation(id, {x,y,z})
end
